spring:
  application:
    name: ui

server:
  port: 8082

square:
  service:
    base-url: http://localhost:8081/square

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    beans:
      enabled: true
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka