spring:
  application:
    name: movie-receiver
  rabbitmq:
    host: localhost
    port: 5672

movie:
  exchange: movie-exchange
  queue-input: q-movie-input
  queue-input-routing-key: movie
  queue-details: q-movie-output
  queue-details-routing-key: movie.details
  queue-error: q-movie-error
  queue-error-routing-key: error

omdb:
  base:
    url: http://www.omdbapi.com/?i=tt3896198&apikey=52d1c7f&t=